### ISSUE TITLE
link to wikipedia page is broken

### ISSUE THREAD

**Issue by gizmomogwai** [Sandman83/vebtree#1]
https://en.wikipedia.org/wiki/Van_Emde_Boas_tree
is the correct link

**Comment by Sandman83** [comment]
How exactly does your link differ from mine? Both work in the same manner for me.

**Comment by gizmomogwai** [comment]
you are right (on github). but on http://code.dlang.org/packages/vebtree the link looks different...
but this is more a problem of code.dlang's markdown renderer i guess?
sorry for the disturbance.

**Comment by Sandman83** [comment]
NP. I filed a bug https://github.com/dlang/dub-registry/issues/404
